name: ExpCollector
version: '1.1'
main: dev.aleksmd.expcollector.ExpCollector
api-version: '1.20'
commands:
  expcollector:
  forceexpcollector:
  expcollectorreload:
    description: Перезагрузить конфигурацию плагина ExpCollector
    usage: /<command>
    permission: expcollector.use
  expbottles:
    description: Открыть GUI с пузырьками опыта
    usage: /expbottles
    permission: expcollector.use